MvcCoreSessionEmpleadosç/Models/Empleado.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcCoreSessionEmpleados.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int emp_no { get; set; }
        [Column("APELLIDO")]
        public string apellido { get; set; }
        [Column("OFICIO")]
        public string oficio { get; set; }
        [Column("SALARIO")]
        public int? salario { get; set; }
        [Column("DEPT_NO")]
        public int? dept_no { get; set; }
    }
}

MvcCoreSessionEmpleadosç/Models/ErrorViewModel.cs
namespace MvcCoreSessionEmpleados.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreSessionEmpleadosç/Controllers/EmpleadosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreSessionEmpleados.Extensions;
using MvcCoreSessionEmpleados.Models;
using MvcCoreSessionEmpleados.Repositories;

namespace MvcCoreSessionEmpleados.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleado repo;
        public EmpleadosController(RepositoryEmpleado repo)
        {
            this.repo = repo;
        }
        public async Task<IActionResult> Index(int? salario)
        {
            if (salario != null)
            {
                int sumaTotal = 0;

                if (HttpContext.Session.GetString("SUMASALARIAL") != null)
                {
                    sumaTotal = HttpContext.Session.getObject<int>("SUMASALARIAL");
                }

                sumaTotal += salario.Value;

                HttpContext.Session.setObject("SUMASALARIAL", sumaTotal);

                ViewData["MENSAJE"] = "SALARIO ALMACENADO";
            }

            List<Empleado> empleados = await this.repo.GetAllEmpleadosAsync();
            return View(empleados);
        }

        public IActionResult SumaSalarial()
        {
            return View();
        }


        public IActionResult IndexSessionSalarios()
        {
            return View();
        }

        public async Task<IActionResult> SessionEmpleado(int? idempleado)
        {
            if (idempleado != null)
            {
                Empleado empleado =
                    await this.repo.FindEmpleadoAsync(idempleado.Value);
                //EN SESSION TENDREMOS ALMACENADOS UN CONJUNTO DE EMPLEADOS
                List<Empleado> empleadosList;

                //DEBEMOS PREGUNTAR SI YA TENEMOS EMPLEADOS EN SESSION
                if (HttpContext.Session.getObject<List<Empleado>>("EMPLEADOS") != null)
                {
                    //RECUPERAMOS LA LISTA DE SESSION
                    empleadosList = HttpContext.Session.getObject<List<Empleado>>("EMPLEADOS");
                }
                else
                {
                    //CREAMOS UNA NUEVA LISTA PARA ALMACENAR LOS EMPLEADOS
                    empleadosList = new List<Empleado>();
                }
                //AGREGAMOS EL EMPLEADO AL LIST
                empleadosList.Add(empleado);
                //ALMACENAMOS LA LISTA EN SESSION
                HttpContext.Session.setObject("EMPLEADOS", empleadosList);
                ViewData["MENSAJE"] = "Empleado " + empleado.apellido + " almacenado correctamente";
            }
            List<Empleado> empleados = await this.repo.GetAllEmpleadosAsync();
            return View(empleados);
        }

        public IActionResult EmpleadosAlmacenados()
        {
            return View();
        }

        public async Task<IActionResult> SessionEmpleadosOk(int? idempleado)
        {
            if (idempleado != null)
            {
                //ALMACENAMOS LO MINIMO
                List<int> idsEmpleados;
                if (HttpContext.Session.getObject<List<int>>("ids") != null)
                {
                    //RECUPERAMOS LA COLEECION
                    idsEmpleados = HttpContext.Session.getObject<List<int>>("ids");
                }
                else
                {
                    idsEmpleados = new List<int>();
                }
                //ALMACENAMOS EL ID
                idsEmpleados.Add(idempleado.Value);
                //ALMACENAMOS EN SESSION LOS DATOS
                HttpContext.Session.setObject("ids", idsEmpleados);
                ViewData["MENSAJE"] = "Empleados OK almacenados";



            }
            List<Empleado> emppleados = await this.repo.GetAllEmpleadosAsync();
            return View(emppleados);
        }

        public async Task<IActionResult> EmpleadosAlmacenadosOK()
        {
            List<int> ids = HttpContext.Session.getObject<List<int>>("ids");
            if (ids == null)
            {
                ViewData["MENSAJE"] = "no hay nada en la lista";
                return View();
            }
            else
            {
                List<Empleado> emps = await this.repo.GetEmpleadosByColeccionIdsAsync(ids);
                return View(emps);
            }
        }


        public async Task<IActionResult> SessionEmpleadosV4(int? idempleado)

        {

            //RECUPERAMOS LA COLECCION

            List<int> idsEmpleados = HttpContext.Session.getObject<List<int>>("ids");

            if (idsEmpleados == null)

            {

                //creamos la coleccion

                idsEmpleados = new List<int>();

            }

            if (idempleado != null)

            {

                //Agregamos el id del empleado

                idsEmpleados.Add(idempleado.Value);

                HttpContext.Session.setObject("ids", idsEmpleados);

                ViewData["MENSAJE"] = "Empleado almacenado: " + idempleado.Value;

            }

            List<Empleado> empleados = await this.repo.GetEmpleadosAsyncNotIn(idsEmpleados);

            return View(empleados);

        }

        public async Task<IActionResult> EmpleadosAlmacenadosV4()

        {

            List<int> idsEmpleados = HttpContext.Session.getObject<List<int>>("ids");

            if (idsEmpleados == null)

            {

                ViewData["MENSAJE"] = "No hay empleados almacenados en session";

                return View();

            }

            else

            {

                List<Empleado> empleados = await this.repo.GetEmpleadosByColeccionIdsAsync(idsEmpleados);

                return View(empleados);

            }

        }

    }
}

MvcCoreSessionEmpleadosç/Views/Empleados/EmpleadosAlmacenados.cshtml
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = "EmpleadosAlmacenados";
    List<Empleado> empleados = Context.Session.getObject<List<Empleado>>("EMPLEADOS");
}

<h1>EmpleadosAlmacenados</h1>

@if (empleados != null && empleados.Count > 0) {
<table class="table table-dark">
    <thead>
        <tr>
            <th>
             emp_no
            </th>
            <th>
             apellido
            </th>
            <th>
              oficio
            </th>
            <th>
               salario
            </th>
            <th>
               dept_no
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in empleados) {
        <tr>
            <td>
                @item.emp_no
            </td>
            <td>
                @item.apellido
            </td>
            <td>
                @item.oficio
            </td>
            <td>
                @item.salario
            </td>
            <td>
                @item.dept_no
            </td>
 
        </tr>
}
    </tbody>
</table>
}
else{
    <h3>No hay nada en session</h3>
}

MvcCoreSessionEmpleadosç/Views/Empleados/EmpleadosAlmacenadosOK.cshtml
@model List<Empleado>
<h1>Empleados Almacenados OK</h1>

<p>
    <a asp-controller="Empleados" asp-action="SessionEmpleadosOk">Volver a la lista de empleados</a>
</p>

@if (Model != null && Model.Count > 0)
{
    <h2>Empleados almacenados en sesión:</h2>
    <ul>
        @foreach (var empleado in Model)
        {

            <li>Empleado ID:@empleado.emp_no</li>  
            <li>Apellido: @empleado.apellido</li>

        }
    </ul>
}
else
{
    <h2>No hay empleados almacenados en sesión.</h2>
    <h1>@ViewData["MENSAJE"]</h1>
}

MvcCoreSessionEmpleadosç/Views/Empleados/EmpleadosAlmacenadosV4.cshtml
@model List<Empleado>
<h1>Empleados Almacenados OK</h1>

<p>
    <a asp-controller="Empleados" asp-action="SessionEmpleadosV4">Volver a la lista de empleados</a>
</p>

@if (Model != null && Model.Count > 0)
{
    <h2>Empleados almacenados en sesión:</h2>
    <ul>
        @foreach (var empleado in Model)
        {

            <li>Empleado ID:@empleado.emp_no</li>
            <li>Apellido: @empleado.apellido</li>

        }
    </ul>
}
else
{
    <h2>No hay empleados almacenados en sesión.</h2>
    <h1>@ViewData["MENSAJE"]</h1>
}

MvcCoreSessionEmpleadosç/Views/Empleados/Index.cshtml
@model List<Empleado>
<h1>Session Salarios</h1>

<p><a asp-controller="Empleados" asp-action="SumaSalarial">Mostrar Suma Salarial</a></p>
<h4>@ViewData["MENSAJE"]</h4>
<table class="table">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Salario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var empleado in Model)
        {
            <tr>
                <td>@empleado.apellido</td>
                <td><a asp-controller="Empleados" asp-action="Index" asp-route-salario="@empleado.salario">Almacenar Salario</a></td>
            </tr>
        }
    </tbody>

MvcCoreSessionEmpleadosç/Views/Empleados/IndexSessionSalarios.cshtml
<h1>Menu Session</h1>
<ul class="list-group">
    <li class="list-group-item"><a asp-controller="Empleados" asp-action="Index">Lista de Empleados</a></li>
    <li class="list-group-item"><a asp-controller="Empleados" asp-action="SessionEmpleado">Lista de SessionEmpleado</a></li>
    <li class="list-group-item"><a asp-controller="Empleados" asp-action="SessionEmpleadosOk">Lista de SessionEmpleadoOk</a></li>
    <li class="list-group-item"><a asp-controller="Empleados" asp-action="SessionEmpleadosV4">Lista de SessionEmpleadoV4</a></li>


</ul>

MvcCoreSessionEmpleadosç/Views/Empleados/SessionEmpleado.cshtml
@model List<Empleado>
<h1>Session Empleados</h1>

<p><a asp-controller="Empleados" asp-action="EmpleadosAlmacenados">Volver a la lista de empleados</a></p>
<h1>@ViewData["MENSAJE"]</h1>
<table class="table">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Salario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var empleado in Model)
        {
            <tr>
                <td>@empleado.apellido</td>
                <td><a asp-controller="Empleados" asp-action="SessionEmpleado" asp-route-idempleado="@empleado.emp_no">Almacenar empleado</a></td>
            </tr>
        }
    </tbody>

MvcCoreSessionEmpleadosç/Views/Empleados/SessionEmpleadosOk.cshtml
@model List<Empleado>
<h1>Session Empleados</h1>

<p><a asp-controller="Empleados" asp-action="EmpleadosAlmacenadosOK">Volver a la lista de empleados</a></p>
<h1>@ViewData["MENSAJE"]</h1>
<table class="table">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Salario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var empleado in Model)
        {
            <tr>
                <td>@empleado.apellido</td>
                <td><a asp-controller="Empleados" asp-action="SessionEmpleadosOk" asp-route-idempleado="@empleado.emp_no">Almacenar empleado</a></td>
            </tr>
        }
    </tbody>

MvcCoreSessionEmpleadosç/Views/Empleados/SessionEmpleadosV4.cshtml
@model List<Empleado>
<h1>Session Empleados</h1>

<p><a asp-controller="Empleados" asp-action="EmpleadosAlmacenadosV4">Volver a la lista de empleados</a></p>
<h1>@ViewData["MENSAJE"]</h1>
<table class="table">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Salario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var empleado in Model)
        {
            <tr>
                <td>@empleado.apellido</td>
                <td><a asp-controller="Empleados" asp-action="SessionEmpleadosV4" asp-route-idempleado="@empleado.emp_no">Almacenar empleado</a></td>
            </tr>
        }
    </tbody>

MvcCoreSessionEmpleadosç/Views/Empleados/SumaSalarial.cshtml
<h1>Suma salarial session</h1>
<p><a asp-controller="Empleados" asp-action="Index">Volver a la lista de empleados</a></p>

@if(Context.Session.GetString("SUMASALARIAL") != null)
{
    <h2>La suma salarial es: @Context.Session.GetString("SUMASALARIAL")</h2>
}
else
{
    <h2>No hay suma salarial almacenada.</h2>
}

MvcCoreSessionEmpleadosç/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreSessionEmpleadosç</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreSessionEmpleadosç.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreSessionEmpleadosç</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="IndexSessionSalarios">Home</a>
                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcCoreSessionEmpleadosç - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>